Feature/card 31
ICEI-PUC-Minas-PMV-SInt/pmv-sint-2021-1-e1-proj-web-t1-sint_2021_01_e1_grupo_01 pull request #43
Opened 2021-06-02 01:21 UTC by alcpl01

2021-06-03 00:11 UTC, erick-ribeiro requested changes

2021-06-03 00:11 UTC, erick-ribeiro commented on astroCal/index.html
> +                                <!-- <div class="card-image" id="imageResponse">
Remover este código comentado

2021-06-03 00:11 UTC, erick-ribeiro commented on astroCal/js/localStorage.js
>  }
adicionar uma linha em branco no final do arquivo

2021-06-03 00:11 UTC, erick-ribeiro commented on astroCal/js/localStorage.js
> +
remover este espaço em branco

2021-06-03 00:11 UTC, erick-ribeiro commented on astroCal/js/localStorage.js
> +    keys.forEach(function(chave, pos){
adicionar um espaço em branco

2021-06-03 00:11 UTC, erick-ribeiro commented on astroCal/index.html
> +
Remover código comentado

2021-06-03 00:27 UTC, tsilva00 approved these changes

2021-06-04 23:35 UTC, erick-ribeiro reviewed
ok

2021-06-04 23:35 UTC, merged